# Number of days of inactivity before an Issue becomes stale
daysUntilStale: 14
# Number of days of inactivity before a stale Issue is closed
daysUntilClose: 14
# Only issues with all of these labels are checked if stale. Defaults to `[]` (disabled)
onlyLabels:
 - awaiting-user-response
# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has no
  recent activity. It will be closed if no further activity occurs. Thank you.
# Comment to post when removing the stale label. Set to `false` to disable
unmarkComment: false
closeComment: >
  Closing as stale. Please reopen if you'd like to work on this further.
# Throttling how many GitHub API calls the bot makes.
# In practice, this helps repo maintainers by limiting the flood
# of notifications as the stale bot catches up with the repo.
limitPerRun: 30
# Limit to only `issues`
only: issues
